import 'package:fodder_distribution/models/fodder_distribution_model.dart';

List<FodderDistributionModel> mockFodderRecords = [
  FodderDistributionModel(
    a_kra: 1,
    jilha: 'पुणे',
    taluka: 'हवेली',
    hangam: 'खरीप',
    pikacheNav: 'मका',
    van: 'आफ्रिकन टॉल',
    ghatakPravarg: 'सर्वसाधारण',
    lakshyankKshetraHe: 25.0,
    lakshyankParimanKvin: 5.0,
    labharthiSankhyaLakshyank: 50,
    vitaritParimanKvin: 4.0,
    sadhyaLabharthiSankhya: 42,
    sadhyaTakkevari: 80.0,
  ),
  FodderDistributionModel(
    a_kra: 2,
    jilha: 'पुणे',
    taluka: 'बारामती',
    hangam: 'खरीप',
    pikacheNav: 'ज्वारी',
    van: 'रुची',
    ghatakPravarg: 'सर्वसाधारण',
    lakshyankKshetraHe: 40.0,
    lakshyankParimanKvin: 8.0,
    labharthiSankhyaLakshyank: 80,
    vitaritParimanKvin: 7.2,
    sadhyaLabharthiSankhya: 72,
    sadhyaTakkevari: 90.0,
  ),
  FodderDistributionModel(
    a_kra: 3,
    jilha: 'सातारा',
    taluka: 'कराड',
    hangam: 'रब्बी',
    pikacheNav: 'बाजरी',
    van: 'न्यूट्रिफीड',
    ghatakPravarg: 'अनु.जाती',
    lakshyankKshetraHe: 15.0,
    lakshyankParimanKvin: 3.0,
    labharthiSankhyaLakshyank: 30,
    vitaritParimanKvin: 1.5,
    sadhyaLabharthiSankhya: 15,
    sadhyaTakkevari: 50.0,
  ),
];
